version: '3.3'

services:
  db:
    container_name: bot_learn
    image: sameersbn/postgresql:12-20200524
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      PG_PASSWORD: $POSTGRES_PASSWORD
      PGDATA: "/var/lib/postgresql/data/pgdata"
    restart: always
    ports:
      - '5432:5432'
    networks:
      - botnet
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data


  tgbot:
    container_name: bot
    build:
      context: .
    command: python bot.py
    restart: always
    networks:
      - botnet
    env_file:
      - ".env"
    volumes:
      - .:/src
    depends_on:
      - db



networks:
  botnet:
    driver: bridge

