"""initial migration

Revision ID: 220803989550
Revises: 8a78713a5a7f
Create Date: 2022-12-20 16:38:15.604652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '220803989550'
down_revision = '8a78713a5a7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
