"""initial migration

Revision ID: 390c6cd342f8
Revises: c2ab33eebcf0
Create Date: 2022-12-20 16:38:35.406660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '390c6cd342f8'
down_revision = 'c2ab33eebcf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
