"""initial migration

Revision ID: 795398d8c316
Revises: a636570eed9d
Create Date: 2022-12-21 13:13:38.520191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '795398d8c316'
down_revision = 'a636570eed9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
