"""initial migration

Revision ID: a636570eed9d
Revises: 390c6cd342f8
Create Date: 2022-12-21 13:10:04.869275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a636570eed9d'
down_revision = '390c6cd342f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
