"""initial migration

Revision ID: c2ab33eebcf0
Revises: 220803989550
Create Date: 2022-12-20 16:38:24.518930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2ab33eebcf0'
down_revision = '220803989550'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
