"""initial

Revision ID: fcdb4bce6b4c
Revises: d9baeaa29e49
Create Date: 2022-12-21 20:10:53.733354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcdb4bce6b4c'
down_revision = 'd9baeaa29e49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
